language: java
install:
- "./gradlew installRoboRioToolchain"
script:
- "./gradlew build"
notifications:
  slack:
    secure: bW1p1FJBZeWC14CjneCSChOrg1FMs9/Mh4Gkzv2GcToCy6WBLX0Ly4apv4ohfGNgq4kHK0yYMlaxs0zBQU7eec6SgVr+HaBhX7fOTPCnHoyhwmEoqOJm8epK22U2yu6QecRFhazyl8vOGgSmtMgn/K7piepvopCPg6FGKyiUsPdxzy7IAmVHNjXGEUcqbMdNCXYAuiHIp+PwT811FRZHCheixCEenzNuOfZVSjsV6d1URZB+y1ZgifjoILEbzDmR1oU4gS+8Yieq0j3kmAQ+TLwnpKzuLnn7whGrV4voTeXu2WkgZ0SkDqpA01E5u9AZTZHWmLfsdHrfx4k9fjKHKdo0/Y8aEK9Ma9m4rcDOsjKTJaS39u9nk8G/1MUqqqzwhXhEd63Y0bbwS4vihFxQXiyuq3GwRJ5VR0PXYqMoQSyiT5JCz6fsNgvaXZnROVEi5sWQU9TLkO5KiRscrHmNtRUcv0NHVFq3qYn7Sk7h0Mo080ooNyK3+2UUE/orlHY+PjkMy/HntF+E69HNmB+f2WtXvEv1aDRa3s7eHv1QJcJgJ/OLSixVJn2A+z4NMEBFPyEOCQqERh6lwTN2GXNLJikLYbKs8uN1DxGXGxrJbTOpFh2BJKWZD53t+KHHXOCo7MRVdSohnOyucv2kocORjQ9glwD64Bq9NAi1tbiyP+A=
